<?php



/**
 *  Change layout of page to have no wrappers when on EFQ call
 *
 */
function inntopia_theme_suggestions_page_alter(array &$suggestions, array $variables) {

	if(strpos(\Drupal::service('path.current')->getPath(), 'inntopia-ajax') !== false){
		$suggestions[] = 'page__ajax';
	}

}



/**
 *  Change layout of html to have no wrappers when on EFQ call
 *
 */
function inntopia_theme_suggestions_html_alter(array &$suggestions, array $variables) {

	if(strpos(\Drupal::service('path.current')->getPath(), 'inntopia-ajax') !== false){
		$suggestions[] = 'html__ajax';
	}

}



/**
 *  Define which template to use
 *
 */
function inntopia_theme($existing, $type, $theme, $path) {
	return array(
		'inntopia_navigation' => array(
			'variables' => array('data' => NULL),
			'template' => 'global/navigation',
		),
		'inntopia_quickcart' => array(
			'variables' => array('data' => NULL),
			'template' => 'cart/quickcart',
		),
		'activities_container' => array(
			'variables' => array('data' => NULL),
			'template' => 'activities/container',
		),
		'activities_filters' => array(
			'variables' => array('data' => NULL),
			'template' => 'activities/filters',
		),
		'activities_listing' => array(
			'variables' => array('data' => NULL),
			'template' => 'activities/listing',
		),
		'activity_detail' => array(
			'variables' => array('data' => NULL),
			'template' => 'activities/product',
		),
		'lodging_container' => array(
			'variables' => array('data' => NULL),
			'template' => 'lodging/container',
		),
		'lodging_filters' => array(
			'variables' => array('data' => NULL),
			'template' => 'lodging/filters',
		),
		'lodging_listing' => array(
			'variables' => array('data' => NULL),
			'template' => 'lodging/listing',
		),
		'lodging_detail' => array(
			'variables' => array('data' => NULL),
			'template' => 'lodging/product',
		),
		'cart' => array(
			'variables' => array('data' => NULL),
			'template' => 'cart/items',
		),
		'checkout_container' => array(
			'variables' => array('data' => NULL),
			'template' => 'checkout/steps',
		),
		'checkout_summary' => array(
			'variables' => array('data' => NULL),
			'template' => 'checkout/summary',
		)
	);
}



/**
 *  Hook page preprocess
 *  (Used mostly for layout setup)
 *
 */
function inntopia_preprocess_page(&$variables) {

	// Adding quickcart and library on every page (since users can open the quickcart from any pages)
	$variables['#attached']['library'][] = 'inntopia/inntopia';
	$variables['inntopia_quickcart'] = ['#theme' => 'inntopia_quickcart', '#data' => null ];

	// Check current path
	$current_path = \Drupal::service('path.current')->getPath();
	$arr_path = explode("/", substr($current_path, 1) );

	// Include common items (sidebar and navigation) on inntopia pages only
	if( isset($arr_path[0]) ) {

		if ($arr_path[0] == "book") {

			$section = ( isset($arr_path[1]) ) ? $arr_path[1] : 'unknown';
			$variables['inntopia_nav'] = ['#theme' => 'inntopia_navigation', '#data' => array( 'section' => $section) ];

			$sidebar = \Drupal::service('inntopia.shopping')->displaySidebar( $section );

			$variables['inntopia_sidebar'] = $sidebar;

		}


		if ($arr_path[0] == "checkout") {

			$sidebar = \Drupal::service('inntopia.checkout')->displaySummary();
			$variables['inntopia_sidebar'] = $sidebar;

		}
	}


}


