<?php

/**
 *  Change layout of page to have no wrappers when on EFQ call
 *
 */
function efq_theme_suggestions_page_alter(array &$suggestions, array $variables) {
	
	if(strpos(\Drupal::service('path.current')->getPath(), 'efq') !== false){
		$suggestions[] = 'page__ajax';
	}
	
}



/**
 *  Change layout of html to have no wrappers when on EFQ call
 *
 */
function efq_theme_suggestions_html_alter(array &$suggestions, array $variables) {
        
	if(strpos(\Drupal::service('path.current')->getPath(), 'efq') !== false){
		$suggestions[] = 'html__ajax';
	}
        
}
