content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  site_admin: 4
  avalanche_report: 5
  weather_forecast: 6
  member: 7
  lifts_and_trails: 8
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_node_type:
  member_page: 'a:1:{s:4:"view";a:1:{i:0;s:13:"authenticated";}}'
