module:
  acl: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advagg: 0
  anchor_link: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  bulk_actions: 0
  cacheflush: 0
  cacheflush_entity: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contact_storage: 0
  contact_storage_export: 0
  content_access: 0
  contextual: 0
  createsend: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  editor_file: 0
  efq: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  exclude_bundles: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  ftp_connect: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  help: 0
  helper: 0
  history: 0
  image: 0
  image_url_formatter: 0
  imagecache_external: 0
  includer: 0
  inntopia: 0
  kint: 0
  libraries: 0
  lifts_trails: 0
  link: 0
  member_content_notification: 0
  menu_block: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  meteo: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pathauto: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  responsive_image: 0
  rest: 0
  role_delegation: 0
  search: 0
  search_exclude_nid: 0
  serialization: 0
  shortcut: 0
  sitemap: 0
  smart_trim: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webcams: 0
  webform: 0
  webform_ui: 0
  wysiwyg_template: 0
  xmlsitemap: 0
  contribute: 1
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  neato: 0
  sunpeaksresort: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
