inntopia_sales_id: '593730'
inntopia_server: live
_core:
  default_config_hash: WrB4NPUhR6RdQXr8MunJ5bjnWOLGvf-WMi7lO7D4WF8
submit: 'Save configuration'
form_build_id: form-p0dDwb3UQ_MH-n4_ysdjTEH9Lvp4VpuYsKOjmcBa2CA
form_token: ll6QY0LC5PnhgWKXmOffhRkqTLp7jXLiymTBS0bEc8E
form_id: inntopia_settings_form
op: 'Save configuration'
