inntopia_sales_id: '8885348'
inntopia_server: stage
_core:
  default_config_hash: WrB4NPUhR6RdQXr8MunJ5bjnWOLGvf-WMi7lO7D4WF8
submit: 'Save configuration'
form_build_id: form-atLRLz7iKotONW0hj_PszeKg8PeVNUJqcce3SKIX2Os
form_token: yi82J-EOi8ZeXjUizVZ444goM5lPEx4BOXZktgcKoAU
form_id: inntopia_settings_form
op: 'Save configuration'
