smtp_on: true
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: website@sunpeaksresort.com
smtp_password: T0dmountain!
smtp_from: website@sunpeaksresort.com
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
