<?php

/**
 *  Change layout of page to have no wrappers when on calling meteo service
 *
 */
function lifts_trails_theme_suggestions_page_alter(array &$suggestions, array $variables) {
	
	if(strpos(\Drupal::service('path.current')->getPath(), 'lifts_trails/generate') !== false){
		$suggestions[] = 'page__ajax';
	}
	
}



/**
 *  Change layout of html to have no wrappers when on calling meteo service
 *
 */
function lifts_trails_suggestions_html_alter(array &$suggestions, array $variables) {
        
	if(strpos(\Drupal::service('path.current')->getPath(), 'lifts_trails/generate') !== false){
		$suggestions[] = 'html__ajax';
	}
        
}
